### PR TITLE
Initial process doc and blog post template

### PR DESCRIPTION
**Pull request by quaid**
- Process doc needs TBDs completed or linked in
- Process doc needs step-by-step descriptions from GH UI

Signed-off-by: Karsten Wade <kwade@redhat.com>

### CODE REVIEW

**Comment by quaid** [comment]
This looks like it's not importing the ES Module, @durandom can you look at this?

    eslint...................................................................Failed
    - hook id: eslint
    - exit code: 1
    
    /home/prow/go/src/github.com/operate-first/blog/gatsby-config.js
    0:0  error  Parsing error: Must use import to load ES Module: /tmp/repoc2tp8v8e/node_env-system/lib/node_modules/eslint/node_modules/eslint-scope/lib/definition.js
    require() of ES modules is not supported.
    require() of /tmp/repoc2tp8v8e/node_env-system/lib/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /tmp/repoc2tp8v8e/node_env-system/lib/node_modules/babel-eslint/lib/require-from-eslint.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
    Instead rename definition.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/repoc2tp8v8e/node_env-system/lib/node_modules/eslint/node_modules/eslint-scope/package.json

**Comment by durandom** [comment]
@quaid the blog is not part of the main website. Can you move your PR to https://github.com/operate-first/operate-first.github.io ?

**Comment by durandom** [comment]
closing, because I'll archive this repo now

**Pull request closed without merging**
